package dev.skybit.pokedex.main.core.utils

// ***** Pokemon Types *****
const val POKEMON_TYPE_NORMAL = "normal"
const val POKEMON_TYPE_FIRE = "fire"
const val POKEMON_TYPE_WATER = "water"
const val POKEMON_TYPE_ELECTRIC = "electric"
const val POKEMON_TYPE_GRASS = "grass"
const val POKEMON_TYPE_ICE = "ice"
const val POKEMON_TYPE_FIGHTING = "fighting"
const val POKEMON_TYPE_POISON = "poison"
const val POKEMON_TYPE_GROUND = "ground"
const val POKEMON_TYPE_FLYING = "flying"
const val POKEMON_TYPE_PSYCHIC = "psychic"
const val POKEMON_TYPE_BUG = "bug"
const val POKEMON_TYPE_ROCK = "rock"
const val POKEMON_TYPE_GHOST = "ghost"
const val POKEMON_TYPE_DRAGON = "dragon"
const val POKEMON_TYPE_DARK = "dark"
const val POKEMON_TYPE_STEEL = "steel"
const val POKEMON_TYPE_FAIRY = "fairy"
